-- Run this in your Supabase SQL Editor
-- Creates user_accounts + claims tables with RLS disabled for simplicity

create table if not exists user_accounts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  email text unique not null,
  password text not null
);

create table if not exists claims (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  user_id bigint references user_accounts(id) on delete cascade not null,
  email text not null,
  spotify_email text
);

-- Disable RLS so anyone can insert/select (simple approach, no auth needed on table)
alter table user_accounts disable row level security;
alter table claims disable row level security;

-- Prevent duplicate emails
create unique index if not exists user_accounts_email_idx on user_accounts (email);
create unique index if not exists claims_user_id_idx on claims (user_id);
