-- Run this in your Supabase SQL Editor
-- Creates the claims table with Row Level Security

create table if not exists claims (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  user_id uuid references auth.users(id) on delete cascade not null,
  email text not null,
  spotify_email text
);

-- Enable RLS
alter table claims enable row level security;

-- Users can only see their own claims
create policy "Users can read own claims"
  on claims for select
  using (auth.uid() = user_id);

-- Users can only insert their own claims
create policy "Users can insert own claims"
  on claims for insert
  with check (auth.uid() = user_id);

-- Optional: prevent duplicate claims (enforced by the app, but this is a safety net)
create unique index if not exists claims_user_id_idx on claims (user_id);
